branches:
  except:
    - gh-pages
language: ruby
rvm:
  - ruby-head
  - "2.3.1"
  - "2.2.5"
  - "2.1.9"
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
script: "bundle exec rake test"
