branches:
  except:
    - gh-pages
language: ruby
rvm:
  - ruby-head
  - "2.4.0"
  - "2.3.3"
  - "2.2.6"
  #- jruby-head
  - jruby
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-3
script: "bundle exec rake test"
