branches:
  except:
    - gh-pages
language: ruby
rvm:
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
  - ruby-head
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
script: "bundle exec rake test"
