branches:
  except:
    - gh-pages
language: ruby
rvm:
  - ruby-head
  - "2.3.1"
  - "2.2.5"
  - "2.1.9"
  - jruby-9.1.5.0
  - rbx-2.2.7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: rbx-2.2.7
script: "bundle exec rake test"
