branches:
  except:
    - gh-pages
language: ruby
rvm:
#  - "2.3.0"
  - "2.2.0"
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode
  - rbx-2.1.1
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.1.1
    - rvm: "1.9.3"
script: "bundle exec rake test"
