branches:
  except:
    - gh-pages
language: ruby
rvm:
  - "2.2.0"
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: "1.9.3"
script: "bundle exec rake test"
